// Code generated by mockery. DO NOT EDIT.

package nats_pubsub_go

import (
	nats "github.com/nats-io/nats.go"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

type Publisher_Expecter struct {
	mock *mock.Mock
}

func (_m *Publisher) EXPECT() *Publisher_Expecter {
	return &Publisher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Publisher) Close() {
	_m.Called()
}

// Publisher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Publisher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Publisher_Expecter) Close() *Publisher_Close_Call {
	return &Publisher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Publisher_Close_Call) Run(run func()) *Publisher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Publisher_Close_Call) Return() *Publisher_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *Publisher_Close_Call) RunAndReturn(run func()) *Publisher_Close_Call {
	_c.Run(run)
	return _c
}

// Publish provides a mock function with given fields: messages
func (_m *Publisher) Publish(messages ...*nats.Msg) error {
	_va := make([]interface{}, len(messages))
	for _i := range messages {
		_va[_i] = messages[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...*nats.Msg) error); ok {
		r0 = rf(messages...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Publisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - messages ...*nats.Msg
func (_e *Publisher_Expecter) Publish(messages ...interface{}) *Publisher_Publish_Call {
	return &Publisher_Publish_Call{Call: _e.mock.On("Publish",
		append([]interface{}{}, messages...)...)}
}

func (_c *Publisher_Publish_Call) Run(run func(messages ...*nats.Msg)) *Publisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*nats.Msg, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(*nats.Msg)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Publisher_Publish_Call) Return(_a0 error) *Publisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Publisher_Publish_Call) RunAndReturn(run func(...*nats.Msg) error) *Publisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function with given fields: message, timeout
func (_m *Publisher) Request(message *nats.Msg, timeout time.Duration) (*nats.Msg, error) {
	ret := _m.Called(message, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 *nats.Msg
	var r1 error
	if rf, ok := ret.Get(0).(func(*nats.Msg, time.Duration) (*nats.Msg, error)); ok {
		return rf(message, timeout)
	}
	if rf, ok := ret.Get(0).(func(*nats.Msg, time.Duration) *nats.Msg); ok {
		r0 = rf(message, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nats.Msg)
		}
	}

	if rf, ok := ret.Get(1).(func(*nats.Msg, time.Duration) error); ok {
		r1 = rf(message, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Publisher_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type Publisher_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - message *nats.Msg
//   - timeout time.Duration
func (_e *Publisher_Expecter) Request(message interface{}, timeout interface{}) *Publisher_Request_Call {
	return &Publisher_Request_Call{Call: _e.mock.On("Request", message, timeout)}
}

func (_c *Publisher_Request_Call) Run(run func(message *nats.Msg, timeout time.Duration)) *Publisher_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*nats.Msg), args[1].(time.Duration))
	})
	return _c
}

func (_c *Publisher_Request_Call) Return(_a0 *nats.Msg, _a1 error) *Publisher_Request_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Publisher_Request_Call) RunAndReturn(run func(*nats.Msg, time.Duration) (*nats.Msg, error)) *Publisher_Request_Call {
	_c.Call.Return(run)
	return _c
}

// NewPublisher creates a new instance of Publisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Publisher {
	mock := &Publisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
