// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	nats_pubsub_go "github.com/SyntaxErrorLineNULL/nats-pubsub-go"
	mock "github.com/stretchr/testify/mock"
)

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

type Subscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *Subscriber) EXPECT() *Subscriber_Expecter {
	return &Subscriber_Expecter{mock: &_m.Mock}
}

// Subscriber provides a mock function with given fields: ctx, subject, queue
func (_m *Subscriber) Subscriber(ctx context.Context, subject string, queue string) (nats_pubsub_go.MessageHandlerInterface, error) {
	ret := _m.Called(ctx, subject, queue)

	if len(ret) == 0 {
		panic("no return value specified for Subscriber")
	}

	var r0 nats_pubsub_go.MessageHandlerInterface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (nats_pubsub_go.MessageHandlerInterface, error)); ok {
		return rf(ctx, subject, queue)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) nats_pubsub_go.MessageHandlerInterface); ok {
		r0 = rf(ctx, subject, queue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(nats_pubsub_go.MessageHandlerInterface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, subject, queue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscriber_Subscriber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscriber'
type Subscriber_Subscriber_Call struct {
	*mock.Call
}

// Subscriber is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - queue string
func (_e *Subscriber_Expecter) Subscriber(ctx interface{}, subject interface{}, queue interface{}) *Subscriber_Subscriber_Call {
	return &Subscriber_Subscriber_Call{Call: _e.mock.On("Subscriber", ctx, subject, queue)}
}

func (_c *Subscriber_Subscriber_Call) Run(run func(ctx context.Context, subject string, queue string)) *Subscriber_Subscriber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Subscriber_Subscriber_Call) Return(_a0 nats_pubsub_go.MessageHandlerInterface, _a1 error) *Subscriber_Subscriber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Subscriber_Subscriber_Call) RunAndReturn(run func(context.Context, string, string) (nats_pubsub_go.MessageHandlerInterface, error)) *Subscriber_Subscriber_Call {
	_c.Call.Return(run)
	return _c
}

// NewSubscriber creates a new instance of Subscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *Subscriber {
	mock := &Subscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
